version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - ${MYSQL_PORT_HOST}:${MYSQL_PORT}
    container_name: CommentDb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
  api:
      image: api-comment-build
      ports:
        - "5000:80"
      depends_on:
        - db
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ConnectionStrings__DefaultConnection={tu_cadena_de_conexión_a_la_base_de_datos}

volumes:
  dbdata:
